---
- name: Ping pycontrol
  hosts: all
  tasks:

    - name: Ping my hosts
      ansible.builtin.ping: null

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Disable root from loggin in via ssh
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^PermitRootLogin
        line: PermitRootLogin no
        state: present
      notify:
        - restart ssh
      tags:
        - security

    - name: Remove the graphical desktop environment
      become: true
      ansible.builtin.apt:
        autoremove: true
        purge: true
        name:
          - raspberrypi-ui-mods
          - vlc*
          - lxde*
          - chromium*
          - desktop*
          - gnome*
          - gstreamer*
          - gtk*
          - hicolor-icon-theme*
          - lx*
          - mesa*
        state: absent
      tags:
        - clean

    - name: GPS Daemon
      become: true
      ansible.builtin.apt:
        name:
          - gpsd
          - gpsd-clients
        state: present
      tags:
        - install

    - name: Configure u-blox 7 GPS receiver device with gpsd
      become: true
      lineinfile:
        path: /etc/default/gpsd
        regexp: ^DEVICES=
        line: DEVICES=/dev/ttyACM0
        state: present
      notify:
        - restart gpsd
      tags:
        - install

    - name: Configure gpsd no wait
      become: true
      lineinfile:
        path: /etc/default/gpsd
        regexp: ^GPSD_OPTIONS=
        line: GPSD_OPTIONS="-n"
        state: present
      notify:
        - restart gpsd
      tags:
        - install

    - name: Chrony - disable network time sync (NTP)
      become: true
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: ^pool .+ iburst
        line: "# anbisle commented out: pool 2.debian.pool.ntp.org iburst"
        state: present
      notify:
        - restart chronyd
      tags:
        - install

    - name: Chrony - synchronizes the system clock to gps time via gpsd
      become: true
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: ^refclock
        line: refclock SHM 0 offset 0.5 delay 0.1 refid GPS
        state: present
      notify:
        - restart chronyd
      tags:
        - install

    - name: Developer environment
      become: true
      ansible.builtin.apt:
        name:
          - cmake
          - g++
          - libbenchmark-dev
          - libboost-dev
          - libgtest-dev
          - libprotobuf-dev
          - libgphoto2-6
          - libgphoto2-dev
          - make
          - protobuf-compiler
          - python-is-python3
          - python3-dev
          - python3.11-minimal
          - tcpdump
        state: present
      tags:
        - install
        - build

  handlers:

    - name: restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: restart gpsd
      ansible.builtin.service:
        name: gpsd
        state: restarted

    - name: restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted
